# Generated by Django 6.0.6 on 2026-07-01 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('student', 'Talaba'), ('employee', 'Xodim'), ('entrepreneur', 'Tadbirkor')], max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='profession',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
