# Generated by Django 6.0.6 on 2026-07-01 05:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_is_verified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BiochemistryTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('glucose', models.FloatField(blank=True, help_text='mmol/L', null=True)),
                ('urea', models.FloatField(blank=True, help_text='mmol/L', null=True)),
                ('creatinine', models.FloatField(blank=True, help_text='µmol/L', null=True)),
                ('uric_acid', models.FloatField(blank=True, help_text='mmol/L', null=True)),
                ('alt', models.FloatField(blank=True, help_text='U/L', null=True)),
                ('ast', models.FloatField(blank=True, help_text='U/L', null=True)),
                ('bilirubin', models.FloatField(blank=True, help_text='µmol/L', null=True)),
                ('cholesterol_total', models.FloatField(blank=True, help_text='mmol/L', null=True)),
                ('hdl', models.FloatField(blank=True, help_text='mmol/L', null=True)),
                ('ldl', models.FloatField(blank=True, help_text='mmol/L', null=True)),
                ('triglycerides', models.FloatField(blank=True, help_text='mmol/L', null=True)),
                ('sodium', models.FloatField(blank=True, help_text='mmol/L', null=True)),
                ('potassium', models.FloatField(blank=True, help_text='mmol/L', null=True)),
                ('calcium', models.FloatField(blank=True, help_text='mmol/L', null=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biochemistry_tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='BloodTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('hemoglobin', models.FloatField(blank=True, help_text='g/dL', null=True)),
                ('wbc', models.FloatField(blank=True, help_text='×10⁹/L', null=True)),
                ('rbc', models.FloatField(blank=True, help_text='×10¹²/L', null=True)),
                ('platelets', models.FloatField(blank=True, help_text='×10⁹/L', null=True)),
                ('hematocrit', models.FloatField(blank=True, help_text='%', null=True)),
                ('esr', models.FloatField(blank=True, help_text='mm/h', null=True)),
                ('crp', models.FloatField(blank=True, help_text='mg/L', null=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HealthDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('doc_type', models.CharField(choices=[('blood_test', 'Qon tahlili'), ('urine_test', 'Siydik tahlili'), ('xray', 'Rentgen'), ('prescription', 'Retsept'), ('other', 'Boshqa')], default='other', max_length=20)),
                ('extracted_text', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('frequency', models.CharField(choices=[('1x_daily', '1×/kun'), ('2x_daily', '2×/kun'), ('3x_daily', '3×/kun'), ('4x_daily', '4×/kun'), ('as_needed', "Zarur bo'lsa"), ('weekly', 'Haftada bir'), ('other', 'Boshqa')], default='1x_daily', max_length=20)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('prescribed_by', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_active', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('symptom_text', models.TextField()),
                ('severity', models.PositiveSmallIntegerField(default=5, help_text='1–10')),
                ('duration_hours', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UrineTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('clarity', models.CharField(blank=True, choices=[('clear', 'Tiniq'), ('slightly_turbid', 'Biroz loyqa'), ('turbid', 'Loyqa')], max_length=20)),
                ('ph', models.FloatField(blank=True, null=True)),
                ('specific_gravity', models.FloatField(blank=True, null=True)),
                ('protein', models.CharField(blank=True, choices=[('negative', 'Manfiy'), ('trace', 'Iz'), ('positive', 'Musbat')], max_length=20)),
                ('glucose', models.CharField(blank=True, choices=[('negative', 'Manfiy'), ('trace', 'Iz'), ('positive', 'Musbat')], max_length=20)),
                ('ketones', models.CharField(blank=True, choices=[('negative', 'Manfiy'), ('trace', 'Iz'), ('positive', 'Musbat')], max_length=20)),
                ('blood', models.CharField(blank=True, choices=[('negative', 'Manfiy'), ('trace', 'Iz'), ('positive', 'Musbat')], max_length=20)),
                ('leukocytes', models.CharField(blank=True, choices=[('negative', 'Manfiy'), ('trace', 'Iz'), ('positive', 'Musbat')], max_length=20)),
                ('nitrites', models.CharField(blank=True, choices=[('negative', 'Manfiy'), ('trace', 'Iz'), ('positive', 'Musbat')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urine_tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
