# Generated by Django 6.0.6 on 2026-07-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_biochemistrytest_bloodtest_healthdocument_medication_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodtest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='healthdocument',
            name='user',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='user',
        ),
        migrations.RemoveField(
            model_name='symptom',
            name='user',
        ),
        migrations.RemoveField(
            model_name='urinetest',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='diabetes_type',
            field=models.CharField(blank=True, choices=[('tip1', 'Tip 1'), ('tip2', 'Tip 2'), ('prediabet', 'Prediabet')], max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='BiochemistryTest',
        ),
        migrations.DeleteModel(
            name='BloodTest',
        ),
        migrations.DeleteModel(
            name='HealthDocument',
        ),
        migrations.DeleteModel(
            name='Medication',
        ),
        migrations.DeleteModel(
            name='Symptom',
        ),
        migrations.DeleteModel(
            name='UrineTest',
        ),
    ]
