# Generated by Django 6.0.6 on 2026-07-01 09:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('glucose_fasting', models.FloatField(blank=True, null=True)),
                ('glucose_postmeal', models.FloatField(blank=True, null=True)),
                ('bp_systolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bp_diastolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pulse', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('medicine_name', models.CharField(blank=True, max_length=150)),
                ('medicine_taken', models.BooleanField(null=True)),
                ('medicine_time', models.TimeField(blank=True, null=True)),
                ('skip_reason', models.TextField(blank=True)),
                ('breakfast', models.CharField(blank=True, max_length=255)),
                ('lunch', models.CharField(blank=True, max_length=255)),
                ('dinner', models.CharField(blank=True, max_length=255)),
                ('physical_activity', models.CharField(blank=True, max_length=255)),
                ('activity_duration', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sleep_hours', models.FloatField(blank=True, null=True)),
                ('stress_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('symptoms', models.TextField(blank=True)),
                ('wellbeing_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
